//Events
export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENT_REQUEST = "GET_EVENT_REQUEST";
export const GET_EVENT_FAIL = "GET_EVENT_FAIL";
export const GET_EVENTS_ACTION= "GET_EVENTS_ACTION";
export const GET_EVENT_ACTION = "GET_EVENT_ACTION";

//Categories
export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_ACTION = "GET_CATEGORIES_ACTION";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

//Users
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";



