export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENT_REQUEST = "GET_EVENT_REQUEST";
export const GET_EVENT_FAIL = "GET_EVENT_FAIL";

export const GET_EVENTS_ACTION= "GET_EVENTS_ACTION";
export const GET_EVENT_ACTION = "GET_EVENT_ACTION";
